# Generated by Django 3.1.1 on 2020-09-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
