# Generated by Django 3.1.1 on 2020-09-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuto', '0003_auto_20200924_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('medal', models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10)),
            ],
        ),
    ]
