# Generated by Django 3.1.1 on 2020-09-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuto', '0004_runner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuto.album', verbose_name='related album'),
        ),
        migrations.AddField(
            model_name='person',
            name='musician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuto.musician', verbose_name='the related musician'),
        ),
        migrations.AddField(
            model_name='person',
            name='sites',
            field=models.ManyToManyField(null=True, to='tuto.Runner', verbose_name='list of runner'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="person's first name"),
        ),
    ]
